name = "eneso-cc"
compatibility_date = "2024-12-14"
compatibility_flags = ["nodejs_compat"]
pages_build_output_dir = ".next"

[env.production]
compatibility_date = "2024-12-14"
compatibility_flags = ["nodejs_compat"]

